version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruhan-webpage
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
