name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_KEY }}
          script: |
            git config --global --add safe.directory /home/debian/repo/ruhan-webpage
            cd ~/repo/ruhan-webpage
            git pull
            docker-compose down
            docker-compose up -d --build
